# This workflow will build and deploy a Next.js app to GitHub Pages
name: Deploy Next.js to GitHub Pages

on:
  push:
    branches: [ "main" ]  # Set this to your default branch
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Using a stable Node.js version
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Configure Next.js for static export
        run: |
          if [ ! -f next.config.js ] || ! grep -q "output:" next.config.js; then
            echo "Configuring Next.js for static export"
            if [ -f next.config.js ]; then
              # Append to existing config
              sed -i "s/module.exports = {/module.exports = {\n  output: 'export',/g" next.config.js
            else
              # Create new config
              echo "/** @type {import('next').NextConfig} */
              const nextConfig = {
                output: 'export',
                images: {
                  unoptimized: true
                }
              };
              
              module.exports = nextConfig;" > next.config.js
            fi
          fi

      - name: Build Next.js app
        run: npm run build

      - name: Create .nojekyll file
        run: |
          mkdir -p out
          touch out/.nojekyll

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: './out'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4